### ISSUE TITLE
Jar Launcher in spring boot incompatible with native image

### ISSUE THREAD

**Issue by eginez** [spring-projects-experimental/spring-graalvm-native#106]
All the launcher utilized when packaging images via the runnable jar is incompatible with native-image

see https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/Launcher.java#L164

Native-image returns a binary  and not a jar file, when probing for `CodeSource`

The idea behind implementing this appropriately avoid is extra work when packaging native-image  and support out of the box creation of images via fat jars
eg:
```native-image -jar [path_to_spring.jar]```

**Comment by sdeleuze** [comment]
With our switch to Spring Boot build image support as our default way to support native images I am not sure this issue is still relevant so I close it.
