### ISSUE TITLE
Ensure docs show setting 'graal mode' flag when agent attached

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-graalvm-native#114]
There are checks in spring framework that take different paths when inside a native-image. For the agent collection of data to work correctly these are the codepaths that should be driven when the agent is attached and running in 'java mode'. The agent does not set this flag yet, so we will need to make sure our docs show that it should be set.

**Comment by aclement** [comment]
Context https://github.com/sbrannen/spring-framework/blob/46bca56460a720ee0c89b9a75fedd4d877ba0f4e/spring-core/src/main/java/org/springframework/core/GraalVmDetector.java#L33-L42

**Comment by sbrannen** [comment]
See also: https://github.com/oracle/graal/issues/2395
