### ISSUE TITLE
Check the application being compiled in case it violates any rules that would prevent successful native-image build

### ISSUE THREAD

**Issue by aclement** [spring-projects-experimental/spring-graalvm-native#118]
There are some things the documentation recommends (proxyBeanMethods=false) that can be enforced via checks so that cryptic problems don't occur later. We should check the app in the feature.

**Comment by aclement** [comment]
I've added a verifier type mechanism - it checks if `proxyBeanMethods=false` has been set for components and produces an error if not set:
```
Fatal error:org.springframework.graal.type.VerificationException: VERIFICATION FAILURE: Component elsewhere.FooBeanFactory does not specify annotation value proxyBeanMethods=false to avoid CGLIB proxies
	at org.springframework.graal.type.Type.verifyProxyBeanMethodsSetting(Type.java:1700)
	at org.springframework.graal.type.Type.verifyComponent(Type.java:1669)
```

HOWEVER, because we have subsitutions in place to avoid pulling in CGLIB, it currently doesn't actually matter if you forget to specify proxyBeanMethods=false - you won't get a CGLIB proxy whatever you do and you won't get an error. This makes the verifier appear painful (it'll report problems that won't cause you issues later). For that reason it is currently defaulting OFF and needs turning ON via `-Dspring.graal.verify=true`. We should determine what we want to do here. The correct thing is *probably* to have the verify error.  This issue remains open until decided what we do for 0.7 and need to doc the option if it remains.

**Comment by aclement** [comment]
document this for 0.7, I don't propose to make it verify by default yet.

**Comment by sdeleuze** [comment]
Notice we now have a hard check for `proxyBeanMethods=false` via https://github.com/spring-projects-experimental/spring-graalvm-native/commit/8f51461215c3c71ddf59a7113bb887d4d7097a7f.

**Comment by aclement** [comment]
Mentioned it in the troubleshooting docs. The option can obviously mean checking more than just this but may remove the `proxyBeanMethods` check from verification later depending on what issues we see come in.
