### ISSUE TITLE
easy switch to graalvm in spring boot

### ISSUE THREAD

**Issue by amorenew** [spring-projects-experimental/spring-graalvm-native#136]
I have read this article about Graal VM and Spring boot
https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/

I wonder do we will have to do 8 steps for running Spring boot on Graal VM
or it will be on IDE or maven(Gradle)

how much effort it would be for the final user to use it?
of those 8 steps how many we need?

![image](https://user-images.githubusercontent.com/2842459/82717480-640bed80-9cad-11ea-9e08-92be840097ee.png)

**Comment by sdeleuze** [comment]
Switching to GraalVM native is not a free lunch, but it will be much easier than that, we will share more information in an upcoming blog post published next week for 0.7 release on https://spring.io/blog/.
