### ISSUE TITLE
@Service missing?

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#141]
Looking at 

https://github.com/spring-projects-experimental/spring-graalvm-native/blob/eb8cfa583597f55b78a54c86ecc3e2133e3cd86b/spring-graalvm-native-configuration/src/main/java/org/springframework/stereotype/Hints.java#L24

I saw that Controller and Component is registry. In my CommandLineRunner Project I used some @Service annotation. Spring in native-image can't find them until I add manually @Service to the reflect-config.json

**Comment by sdeleuze** [comment]
@aclement Do you think we could support meta-annotations in order to be able to only configure `@Component` and support user-defined ones?

**Comment by aclement** [comment]
Very surprised we didn't have a sample that got into this space. Fixed it up, yes @sdeleuze with smarter recognition rather than just adding another entry to the hint.
