### ISSUE TITLE
Running from master?

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#147]
Hi!

I saw this project contains a lot of fixes since 0.6.1.RELEASE

Is there a documentation available how to compile this project from master, then use the built artefacts in an other project?

I also found a snapshot repo but it looks like the version are very old.

https://repo.spring.io/snapshot/org/springframework/experimental/spring-graal-native/

Maybe it possible to push snapshots from master directly.

**Comment by aclement** [comment]
Yes we should probably have a copy of the docs that talk about how to consume snapshots on the bleeding edge.

The project was renamed (again...) recently so the recent snapshots for 0.7 are here: 
https://repo.spring.io/snapshot/org/springframework/experimental/spring-graalvm-native/0.7.0.BUILD-SNAPSHOT/

We will shortly polish the docs for 0.7 but they aren't far removed from 0.6.

The `build.sh` in the project route will do a `mvn clean install` to put the snapshot in your local maven repo, then you can depend on that. Or...

For how to use it in your own project, this is roughly the route:
https://repo.spring.io/milestone/org/springframework/experimental/spring-graal-native-docs/0.6.0.RELEASE/spring-graal-native-docs-0.6.0.RELEASE.zip!/reference/index.html#_set_up_the_sample_project

Just have to keep in mind when reading that page:
- you need the snapshot repository, not the milestone one  in the repository and pluginRepositories sections:
```
                <pluginRepository>
                        <id>central</id>
                        <url>https://repo.maven.apache.org/maven2</url>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                </pluginRepository>
```
```
                <repository>
                        <id>central</id>
                        <url>https://repo.maven.apache.org/maven2</url>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                </repository>
```
The name of the dependency for the main graal support is:
```
    <dependency>
        <groupId>org.springframework.experimental</groupId>
        <artifactId>spring-graalvm-native</artifactId>
        <version>0.7.0.BUILD-SNAPSHOT</version>
    </dependency>
```

But the rest of it should work. Let me know if it doesn't.

**Comment by aclement** [comment]
Fixed my massive copy paste error in the previous comment! repo references should now be ok.

**Comment by jkroepke** [comment]
Thanks,

i‘ll try it. I hope I will had less to be define in the reflect-config. Is this the goal of the project?

**Comment by jkroepke** [comment]
I can confirm, it works with your described above.

And my test project will compile and run successfully now. Thanks for your work!

**Comment by aclement** [comment]
Thanks for confirming it works for you. The goal of the project is to make it easier to use Graal with Spring - one aspect of that is making it easier to manage all that configuration and where possible remove the need to craft it manually. Sometimes the feature will handle it, sometimes the agent will handle it. I've added a comment to the docs about snapshot repositories.
