### ISSUE TITLE
Use the new lightweight Tomcat distribution

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#151]

**Comment by sdeleuze** [comment]
To be polished but if think we can close this issue as we now use the Maven plugin to create a lightweight version of the Tomcat distribution.

**Comment by sdeleuze** [comment]
I reopen this issue in order to use `tomcat-embed-programmatic:9.0.38-dev` that @fhanik is about to publish.

**Comment by fhanik** [comment]
Artifact published to `libs-milestone-local`. Still getting some errors

**Comment by fhanik** [comment]
Published working `tomcat-embed-programmatic:9.0.38.1-dev` to libs-milestone-local
