### ISSUE TITLE
Refactor actuator hints

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#160]
With latest changes, if actuator dependency in uncommented in `spring-petclinic-jpa` sample, the following error is thrown: `Fatal error:java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/web/reactive/AbstractWebFluxEndpointHandlerMapping`.

I think we should split https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-configuration/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/servlet/Hints.java in at least 2 distinct hints in order to avoid trying to include WebFlux classes for WebMvc actuator.

Any chance you could have a look @aclement ?

**Comment by aclement** [comment]
I will take a look. Although need to see the failure for myself - if it is purely a reference from a hint not being found, it shouldn't make any real difference. But maybe I'm getting the impression we are adding something which is then failing in what it is looking for, let me see.

**Comment by aclement** [comment]
I think there is perhaps a GraalVM bug lurking there actually - with it not coping with not finding a type. However, I have taken a pass at making the webflux parts of the actuator more conditional and now it works - at least in the `spring-petclinic-jpa` project, and I reactivated the actuator dependency in there.

There is much much more work that could be done here to optimize what is included for actuator based projects.

**Comment by sdeleuze** [comment]
Ok thanks I will let the bug open but targeting 0.8.0 instead since with 112d09090862fbe38cb53ec32e24fe1209ff4fb2 we are fine for 0.7.0.

**Comment by sdeleuze** [comment]
I think we are fine or close to be with recent refactorings, thanks for handling that @aclement.
