### ISSUE TITLE
Switch all samples on pure Maven/Gradle builds and leverage Paketo buildpacks

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#165]
@nebhale and his team has already implemented tiny image support suitable for production, usable with:
```xml
<plugin>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-maven-plugin</artifactId>
	<configuration>
		<image>
			<builder>nebhale/native-image-builder:0.8.0-20200727.100158-91</builder>
			<env>
				<BP_BOOT_NATIVE_IMAGE>1</BP_BOOT_NATIVE_IMAGE>
				<BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
					-Dspring.native.remove-yaml-support=true
					-Dspring.native.remove-jmx-support=true
					-Dspring.spel.ignore=true
					-Dspring.xml.ignore=true
					-Dspring.backgroundpreinitializer.ignore=true
				</BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
			</env>
		</image>
	</configuration>
</plugin>
```
You even don't need to add `spring-graalvm-native` dependency to the classpath!

What I really like in this approach is that it provide seamless integration with Spring Boot with both [Maven plugin](https://docs.spring.io/spring-boot/docs/2.3.x/maven-plugin/reference/html/#build-image) and [Gradle plugin](https://docs.spring.io/spring-boot/docs/2.3.x/gradle-plugin/reference/html/#build-image). Also dealing directly with Linux containers regardless of the platform is IMO a good thing.

I think we miss 2 things to generalize that:
 - It would be great for the builder to exclude the builder own `spring-graalvm-native` version when it is specified as a dependency in the classpath.
- I think we would need a dev-oriented image that would replace conceptually our `spring-graalvm-native` one and that could integrate the debugging support @dsyer has worked on. This could be then used for #154 in 0.9.

**Comment by nebhale** [comment]
> It would be great for the builder to exclude the builder own spring-graalvm-native version when it is specified as a dependency in the classpath.

[Done](https://github.com/paketo-buildpacks/spring-boot/commit/62616b2c269d37156e95b7aa3e28f313ead5e732).

> I think we would need a dev-oriented image...

What kind of things do you think this would need?  All of the buildpacks will work on `ubuntu:bionic` which has a shell (although admittedly not a lot else) and `full` which is `ubuntu:bionic` plus [an extra 121 packages](https://github.com/paketo-buildpacks/stacks/blob/main/packages/full/run)

**Comment by sdeleuze** [comment]
@nebhale Thanks. As discussed recently, we would need a developer oriented variant with GDB that we would use for #154 for example. I tend to think it is orthogonal to `tiny`/`bionic`/`full`, it would be more `dev` and `prod` variants.
