### ISSUE TITLE
0.7.1 native-image.properties failed. Property 'Args' contains invalid entry '--install-exit-handlers'  

### ISSUE THREAD

**Issue by costap** [spring-projects-experimental/spring-graalvm-native#186]
Hi guys

I'm getting this error after upgrading to 0.7.1,  2.3.1 boot and 20.1.0 Graal, before was on 0.6.0 and building ok.

{code}
Error: Processing jar:file:///Users/pedro.costa/.m2/repository/org/springframework/experimental/spring-graalvm-native/0.7.1/spring-graalvm-native-0.7.1.jar!/META-INF/native-image/org.springframework.experimental/spring-graal-native/native-image.properties failed                                                                                                                                          Caused by: com.oracle.svm.driver.NativeImage$NativeImageError: Property 'Args' contains invalid entry '--install-exit-handlers'  
{code}

Any idea?

Thanks

**Comment by sdeleuze** [comment]
Could you double check you are using GraalVM 20.1.0? This option is not supported on 20.0.0 but is on 20.1.0.

**Comment by costap** [comment]
Hi Sebastien
Very sorry yes, I updated the graalvm plugin version in the pom but forgot about the jvm version installed in my machine which was still 20.0.0
After upgrading everything it works
closing
Thanks!
