### ISSUE TITLE
Support for @ConfigurationProperties in functional mode

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#201]
There might be some changes in Spring Boot that obviate the need for this eventually, but I found that there are a bunch of reflective bean definitions introduced by `ConfigurationPropertiesBindingPostProcessor`:

```
  {
    "name": "org.springframework.boot.context.properties.ConfigurationPropertiesBeanDefinitionValidator",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.springframework.boot.context.properties.BoundConfigurationProperties",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.springframework.boot.context.properties.ConfigurationPropertiesBinder$Factory",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
```

It's quite reasonable to expect to be able to use `@ConfigurationProperties` even in functional mode. Might not be needed for all apps, e.g. not for Spring Fu, but anything else that uses the existing properties classes would benefit from not having to manually specify the JSON above.

**Comment by aclement** [comment]
Isn't this really the same as #205  ?

**Comment by dsyer** [comment]
Actually no. Although on the face of it, I agree it is hard to tell. This one was fixed in Spring Boot (it’s about the helpers that do the binding).
