### ISSUE TITLE
Add reflection configuration for @ConfigurationProperties beans in functional mode

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#205]
Spring Boot does require reflective access to `@ConfigurationProperties` beans in order to bind to the `Environment`. It's a pretty basic feature in Spring Boot, so I feel like we could support it even in functional mode (it already works in default mode). Maybe not with Spring Fu, which raises the question of whether we need another mode.

**Comment by sdeleuze** [comment]
Depends on #224.

**Comment by aclement** [comment]
I believe working now.
