### ISSUE TITLE
Find why we need to use a Maven profile for spring-boot-maven-plugin with Maven based builds

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#211]
This should not be necessary:
```
        <profile>
            <id>jar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

**Comment by aclement** [comment]
Just my 2c. As I recall, my only fiddling around this was ensuring that the feature and native-image ran against the pre-packaged stuff and not the packaged boot jar. That was just perhaps a sign that it was triggering as part of the wrong maven goal, and maybe we've fixed that now.

**Comment by sdeleuze** [comment]
Not a hard requirement anymore due to #165 so I close this one which should be solved on GraalVM side.
