### ISSUE TITLE
Modularize proxy and ressource configuration

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#215]
Since hints can now include proxy and resource configuration, we should now move those elements from current [JSON based static configuration](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-configuration/src/main/resources) to hints.

In 0.9 I would even go as far as as doing the same for reflection and initialization config and totally remove those static files and related processing mechanism to lower the maintenance cost and cognitive load. That would also allow more check during compilation. I will create a related issue.

**Comment by aclement** [comment]
Resources is just about done, when I make the next commit what remains in `resources.json` is:
```
    // Kotlin
    {"pattern":"META-INF/.*.kotlin_module$"},
    {"pattern":".*.kotlin_builtins"}
```
We could consider these general SpringApplicationHints, so always active, they just won't cause anything to be included in the image if they don't match anything on the classpath. Is that ok @sdeleuze ?

**Comment by sdeleuze** [comment]
@aclement I think my proposal would to leverage the recent classpath trigger to include these only when `kotlin.Unit` in in the classpath.

**Comment by aclement** [comment]
`resources.json` is empty! That is probably all I can face doing for 0.8.0, it's quite painful tedious work.  initialization/proxies lists have shrunk, but aren't empty.

**Comment by sdeleuze** [comment]
Yeah, thanks a lot for tackling this, I guess we can close this issue now.
