### ISSUE TITLE
Support reflection hint with modes = Mode.FUNCTIONAL

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#224]
Tomcat hints introduced with https://github.com/spring-projects-experimental/spring-graalvm-native/commit/3260317ff675d4a1033d6571904fab7fd96c7b5e seems to work on `springmvc-tomcat` but not with `jafu-webmvc`.

**Comment by aclement** [comment]
I know we talked about an additional attribute indicator that the trigger should be treated as a presence indicator, but in the interim whilst we bake the idea I did something simpler: if your hint trigger is not a 'spring thing' (configuration/importregistrar/importselector/condition or marked AtImport) then it treats it as a presence checking trigger, and if around on a particular run the hint will apply. If it hangs together I will make it a more first class choice via another indicator flag.

So the 'default hints' that apply are those that have no trigger or have a trigger that is not a well known spring thing and that don't exclude themselves by any mode constraint they specify. This latter check enables us to activate some types required for annotation based configuration to work (they have no trigger but they specify they are only valid in non functional modes).

Seems to behave at the moment. Will revisit if functional init sample not working.
