### ISSUE TITLE
Spring Data commons Configuration classes

### ISSUE THREAD

**Issue by bajajyog** [spring-projects-experimental/spring-graalvm-native#232]
I am trying to create native image for Spring Boot(2.4.0 Snapshot), jersey, hibernate micro service. my micro service uses spring data commons. there are configuration classes in spring data commons which do not have proxy bean method false.
This causes my native image to fail at run time. Appreciate  to take care of this change at earliest in 2.4.0.SNAPSHOT

**Comment by aclement** [comment]
This is being handled here https://jira.spring.io/browse/DATACMNS-1736

**Comment by sdeleuze** [comment]
Duplicates of #228.
