### ISSUE TITLE
Document entity scan required for Native image

### ISSUE THREAD

**Issue by bajajyog** [spring-projects-experimental/spring-graalvm-native#235]
Spring Boot 2.4.0.Snapshot
Spring Graal : 0.8.0.Snapshot
 Spring boot , Jersey and JPA/Hibernate microservice. I am able to build native image for the microservice successfully.
Using Spring LocalContainerEntityManagerFactoryBean, we are creating Entity Manager factory. In LocalContainerEntityManagerFactoryBean, we are setting package to scan. in native image when i ran, it is failing, as it is not able to find named query defined in JPA entity. Does any issue for entity scan in native image. This runs file, if i run my code as spring boot app without native image  Any help to resolve this issue will be of great help.

**Comment by sdeleuze** [comment]
Did you try to use `hibernate-enhance-maven-plugin`  like in https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-samples/jpa/pom.xml#L105-L125 and setting https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-samples/jpa/src/main/resources/hibernate.properties?

**Comment by sdeleuze** [comment]
Turning this issue into a documentation one.
