### ISSUE TITLE
Rename modes and activate them automatically

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#236]
- `functional` : activated when `org.springframework.init.func.InfrastructureInitializer`, `org.springframework.fu.kofu.KofuApplication` or `org.springframework.fu.jafu.JafuApplication` are on the classpath.
- Rename `hybrid` to `agent` : if existing config is visible.
- Rename `default` to `reflection`: if no existing config and not spring-fu/spring-init related.
- Rename `agent` to `init`: initialization config only for debugging/hands-off, configured manually.

**Comment by aclement** [comment]
Just one clarification. agent is inferred if existing config is visible *and* it contains SpringBootApplication. I didn't want to infer agent just from noticing config in 3rd party dependencies.
