### ISSUE TITLE
Support @Configuration without proxyBeanMethods = false

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#248]
Since our goal is to support Spring Boot application "unchanged", it would be nice to find a way to not create a CGLIB proxy when not needed. I tend to think current Framework behavior is fine (it can't really analyze at runtime if CGLIB proxies are effectively needed or not). I think we should add `proxyBeanMethods = false` when possible (when there is no cross `@Bean` method invocation) at build time. Not sure if that should be done here or at `spring-init` level and not sure yet how (byte code analyze and manipulation to be able to target libraries as well maybe?). cc @aclement @dsyer @jhoeller

**Comment by aclement** [comment]
> it can't really analyze at runtime if CGLIB proxies are effectively needed or not

Is there not a trivial special case where you have a SpringBootApplication annotated type with just a main method but no @Bean methods? In that case no proxy is required (I think). This would address the case of running something straight from start.spring.io. I do agree the general case would be hard/impossible to work out.

**Comment by sdeleuze** [comment]
It is possible but I think such "trick" would be confusing for users, as soon as they will add `@Bean` it will fail. Or maybe if they add 2 `@Bean` method but you see that will be even more confusing. I think it is preferable to handle that via a transformation on spring-init side, it will be easier to debug.

**Comment by sdeleuze** [comment]
Let's try to see if we can modify the default `proxyBeanMethods` value via a substitution and add a build time check to fail the build if we detect cross `@Bean` method invocations (with a flag to opt-out).

**Comment by sdeleuze** [comment]
@aclement Pushed, but we need to fix the cross `@Bean` invoction check that seems not effective. I did a try with the verify option enabled and this code in the application class:
```
	static class Foo {

	}

	static class Bar {

		private Foo foo;

		public Bar(Foo foo) {
			this.foo = foo;
		}

	}

	@Bean
	public Foo foo() {
		return new Foo();
	}

	@Bean
	public Bar bar() {
		return new Bar(foo());
	}
```
Also if the error in effective we could probably remove the warning.

**Comment by aclement** [comment]
Here we go:
```
Caused by: java.lang.IllegalStateException: ERROR: in 'com.example.commandlinerunner.CommandlinerunnerApplication' these methods are directly invoking methods marked @Bean: [bar] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection.
```

**Comment by aclement** [comment]
Currently it is still only scanning what is in the app, not the components in the dependencies. I will activate that after a first check just amongst the samples to see if anything fires this exception.

**Comment by aclement** [comment]
Basic samples are not hitting verify errors. I broadened it to checking all components that go through the main processing loop (so it will check things obtained from dependencies that we think might be used in the app, rather than scanning everything on the class path).  Committed it.

**Comment by richvim** [comment]
Is there any way to have it be explicit? Even with latest, it was still hanging on some of my dependancies which didn't have the decorator.

**Comment by sdeleuze** [comment]
@richvim Could you please provide a repro of the issue you are facing?
