### ISSUE TITLE
Replace modes hints attribute by a boolean flag

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#257]
In order to replace `modes= {Mode.REFLECTION,Mode.AGENT}` by a more focused attribute. Maybe `applyToFunctional` with a default to `true`. We should update the doc accordingly.

See related 9fbfc0e89c4fa53a498bb66c4177de7bfd3e9965 commit.

**Comment by aclement** [comment]
I think this is done - waiting on the build to confirm its ok.
