### ISSUE TITLE
Use ConfigDataLoaders instead of ConfigFileApplicationListener in functional mode

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#262]
See https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-substitutions/src/main/java/org/springframework/boot/SpringBootFactories.java#L111

**Comment by sdeleuze** [comment]
`ConfigTreeConfigDataLocationResolver`, `ResourceConfigDataLocationResolver`, `ConfigTreeConfigDataLoader` and `ResourceConfigDataLoader` are package private so I move this issue to 0.8.2 in order to allow us and Spring Boot team to solve this. cc @philwebb

**Comment by philwebb** [comment]
Fixed in https://github.com/spring-projects/spring-boot/issues/23434
