### ISSUE TITLE
Optimize actuators hints to only add needed reflection entries

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#270]
In addition to the more long term #259, I create this issue to optimize actuators hints based on the diff between a basic Spring MVC app and the same with the actuator.
[diff.txt](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5188677/diff.txt)

Some reflection entries seems suspicious like `Charset`, `File`, `JsonGenerator`, `JsonParser`, `LinkedMultiValueMap`, `Locale`, `MapperFeature`, `RequestMethod`, etc. As pointed out by @dsyer they seems to come from `ConfigurationPropertiesReportEndpointAutoConfigurationHints`. Could we be more specific about those reflection entries to not configure all methods? Also that endpoint isn't even enabled by default, so can we change the logic there, e.g. evaluate `@ConditionalOnAvailableEndpoint` at build time? It would need to actually create an `Environment`.

If limited changed with significant impact on Boot are possible we should identify them.

**Comment by aclement** [comment]
First big pass done - image sizes down by ~5Meg, RSS down 4Meg on actuator-webmvc. This is with a more sophisticated verify.sh script that actually exercises endpoints.

**Comment by aclement** [comment]
Other enhancements are baking, but will take a while to sort out.

**Comment by sdeleuze** [comment]
Ok so I guess we can close this one for `0.8.1` and tackle more long term ones via #259, thanks for working on this @aclement.
