### ISSUE TITLE
/features endpoint not behaving the same in native image

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#272]
Might need some changes in Spring Cloud? First we need some reflection hints for `org.springframework.cloud.client.actuator.FeaturesEndpoint` and all the nested classes that are used in the endpoint method (`Features` and `Feature`).

Here's the result from a native image when you do that:

```
$ curl localhost:8080/actuator/features
{"enabled":[{"type":"org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient","name":"DiscoveryClient","version":null,"vendor":null}],"disabled":["LoadBalancerClient"]}
```

same app in a regular JVM:

```
$ curl localhost:8080/actuator/features
{"enabled":[{"type":"org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient","name":"DiscoveryClient","version":"3.0.0-SNAPSHOT","vendor":"Pivotal Software, Inc."},{"type":"org.springframework.cloud.client.discovery.composite.reactive.ReactiveCompositeDiscoveryClient","name":"ReactiveDiscoveryClient","version":"3.0.0-SNAPSHOT","vendor":"Pivotal Software, Inc."}],"disabled":["LoadBalancerClient","ReactiveLoadBalancer"]}

**Comment by dsyer** [comment]
Also the /health endpoint is different. It fails to pick up the Spring Cloud health indicators (which are present as beans) for discovery client, I think for the same reason - there's an `@ConditionalOnBean` that is not matching where it should for discovery clients.

**Comment by aclement** [comment]
The data concerning version/vendor in the endpoints is driven by pulling it out of MANIFEST.MF - this doesn't work in GraalVM - issue is https://github.com/oracle/graal/issues/2228

**Comment by aclement** [comment]
`/features` is now working in that it returns the same number of entries in the image as in java mode. Looking at `/health` now.

**Comment by aclement** [comment]
The same fix also addressed 'most of' the `/health` differences (discovery client stuff is there).  These are the differences remaining:

JVM:
```
  "clientConfigServer": {
      "status": "UNKNOWN",
      "details": {
        "error": "no property sources located"
      }
    },
```

native-image:
```
    "clientConfigServer": {
      "status": "UNKNOWN"
    },
```

JVM:
```
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 499963174912,
        "free": 97547210752,
        "threshold": 10485760,
        "exists": true
      }
    },
```
native-image:
```
    "diskSpace": {
      "status": "UP"
    },
```

**Comment by dsyer** [comment]
LGTM. The "details" field is a `Map<String,Object>`, so we probably don't support serializing that in general (via Jackson) yet. Should probably be a separate issue.

**Comment by imosapatryk** [comment]
Hi @aclement has the issue been resolved when it comes to: 

`  "clientConfigServer": {
      "status": "UNKNOWN",
      "details": {
        "error": "no property sources located"
      }
    }`

I've been trying to make it working on Spring Boot 2.4.2 but still receive the same...
