### ISSUE TITLE
Nested component class not registering hints on @RestController

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#275]
The webflux-netty sample has this code:

```java
@SpringBootApplication(proxyBeanMethods = false)
public class WebfluxApplication {

	public static void main(String[] args) {
		SpringApplication.run(WebfluxApplication.class, args);
	}

	@RestController
	class Foo {

		@GetMapping("/")
		public String greet() {
			return "hi!";
		}
	}

}
```

It's unusual to have a non-static nested class that works as a `@Component`, and I think it is working, but by accident. If you delete the `Foobar` class from this sample it fails at runtime:

```
Caused by: org.springframework.core.annotation.AnnotationConfigurationException: Attribute 'value' in annotation [org.springframework.web.bind.annotation.RestController] is declared as an @AliasFor nonexistent attribute 'value' in annotation [org.springframework.stereotype.Controller].
```

because the reflection and resource configurations are not added for `@Controller`. So even though there *is* a `@RestController` (in the nested class), it is not causing the Webflux annotation hints to be applied.

**Comment by sdeleuze** [comment]
Tentatively scheduled for 0.8.1.

**Comment by aclement** [comment]
No new test added but tested webflux-netty chopped up as per the description.

**Comment by sadew145** [comment]
@aclement I am sorry for commenting on closed ticket but I am using boot 2.4.0-m3 and spring graalvm 0.8.1 and I still get this issue.
`ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class []; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: A
ttribute 'value' in annotation [org.springframework.web.bind.annotation.RestController] is declared as an @AliasFor nonexistent attribute 'value' in annotation [org.springframework.stereotype.Controller].
`

**Comment by dsyer** [comment]
The sample above is working though right? You might need to supply a few more details, and maybe report as a new issue.

**Comment by sadew145** [comment]
@dsyer I created a new issue and attached all things i could think of in the zip. Please check out #329
