### ISSUE TITLE
Support for JSON rendering of maps

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-graalvm-native#279]
As observed in #272 it seems like we cannot yet support serializing `Map<String,Object>` to JSON, even if the values are simple primitiveish types (like String). It would be useful to work out what the barrier is. Probably just some reflection configuration on `HashMap` or similar.

**Comment by aclement** [comment]
For the case I'm aware of - with the diskSpace endpoint - I've fixed it so the native-image returns the same thing. The issue was reflective access to the Health class that contains the details map. I guess that will fix many cases where the details are being missed.

**Comment by sdeleuze** [comment]
Based on @aclement comment I think this is fixed please reopen if that's not the case.
