### ISSUE TITLE
Fix Tomcat native performance issue

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#306]
As found by @dsyer there is something really weird about Tomcat performance on native, and hat's likely a regression because previously observed performance were ok:
```
Requests per second:    0.97 [#/sec] (mean)
Time per request:       1032.493 [ms] (mean)
Time per request:       1032.493 [ms] (mean, across all concurrent requests)
```
This issue is not present on the JVM nor with Netty on native.

**Comment by dsyer** [comment]
This one is really weird because it only happens with Apache Bench. If I just do cURL in a tight loop it works fine. I can't see any obvious reason why.

**Comment by sdeleuze** [comment]
HTTP 1.0 support issue maybe since ab is using it?

**Comment by dsyer** [comment]
I thought of that, but I tried with cURL and HTTP 1.0 and couldn’t reproduce.

**Comment by sdeleuze** [comment]
Ok so maybe parallel request processing ... Maybe a thread pool configuration with a size set to 1 on native via a specific code path.

**Comment by fhanik** [comment]
Confirmed the issue. Does not appear to be concurrency related as the delay happens on a single thread too. Continuing investigation...stand by

**Comment by fhanik** [comment]
I believe this to be a regression in GraalVM/native-image.

It appears as if you do a single request, there isn't any data coming behind and actually flushing out the request to the socket.
So on the Tomcat side, it appears that the request is completed, for Apache Bench, it has not received the final packets.

This problem does not exist in Graal 19.2

## GraalVM Version 19.2.1 CE

### Single Request

`Requests per second:    481.46 [#/sec] (mean)`

### 50 Concurrent Request

`Requests per second:    585.23 [#/sec] (mean)`

## GraalVM Version 20.1.0-dev CE

### Single Request

`Requests per second:    1.00 [#/sec] (mean)`

### 50 Concurrent Request

`Requests per second:    366.44 [#/sec] (mean)`

## GraalVM Version 20.1.0-dev CE

### Single Request

`Requests per second:    1.00 [#/sec] (mean)`

### 50 Concurrent Request

`Requests per second:    366.44 [#/sec] (mean)`


## Wireshark observation

### Graal 19.2
![image](https://user-images.githubusercontent.com/607429/94965006-8c9fc180-04af-11eb-87d5-62e278307392.png)

### Graal 20.2
![image](https://user-images.githubusercontent.com/607429/94965044-9d503780-04af-11eb-94ff-a81b21aaab72.png)

**Comment by sdeleuze** [comment]
This issue is Java 8 specific and should be fixed on GraalVM side via https://github.com/oracle/graal/issues/2902 so I close this one.
