### ISSUE TITLE
Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by RajeevKumarMarrapu** [spring-projects-experimental/spring-graalvm-native#308]
I'm getting the following error when I run a build script in [webmvc-tomcat](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/webmvc-tomcat) sample

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.springframework.boot.context.properties.bind.Bindable was unintentionally initialized at build time. To see why org.springframework.boot.context.properties.bind.Bindable got initialized use -H:+TraceClassInitialization
```

I'm using OS: Ubuntu-20.04
GraalVM: 20.2.0.r8 or 20.2.0.r11 (Issue is reproduced in both versions)
spring-graalvm-native artifact version: 0.8.0

Complete error log can be available here [error.log](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5281430/error.log)

**Comment by sdeleuze** [comment]
`0.8.0` is designed to work with Spring Boot `2.4.0-M2`. Please use `0.8.1` that we just released with Spring Boot `2.4.0-M3`.

**Comment by RajeevKumarMarrapu** [comment]
@sdeleuze Thanks for the quick response. Actually I did tried with above mentioned version. but I'm getting the following error
`[ERROR] Failed to execute goal on project webmvc-tomcat: Could not resolve dependencies for project com.example:webmvc-tomcat:jar:0.0.1-SNAPSHOT: Failure to find org.springframework.experimental:spring-graalvm-native:jar:0.8.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by sdeleuze** [comment]
I confirm we are talking about `0.8.1` not `0.8.2` also make sure to configure the related repository https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.1/spring-graalvm-native-docs-0.8.1.zip!/reference/index.html#_add_the_repositories. If you build the samples from sources you should use https://github.com/spring-projects-experimental/spring-graalvm-native/tree/0.8.1.
