### ISSUE TITLE
Question about injecting a concrete class in spring-graalvm-native

### ISSUE THREAD

**Issue by dzou** [spring-projects-experimental/spring-graalvm-native#313]
I've been trying out `spring-graalvm-native` and trying to get it working with some non-officially supported libraries by `spring-graalvm-native` in Spring such as Spring Cloud GCP.

I've been testing it on a simple Spring boot sample, [source code here](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/15/files?file-filters%5B%5D=.java).

Basically didn't have to modify the code much, just added `@SpringBootApplication(proxyBeanMethods = false)` and added some custom reflection configuration and it's pretty close to working.

However I ran into this error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'workService' could not be injected as a 'com.example.WorkService' because it is a JDK dynamic proxy that implements:

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.
```

In my code I have a `WorkService` class annotated with `@Service` and I try to inject this into another class. So is the solution to this problem to just create an interface for my `WorkService` class and inject that? Are GraalVM-compiled apps unable to inject a concrete class in certain situations?

**EDIT:** I just tried to make an interface for `WorkService` and having Spring inject the interface instead. I got a new error:

```
Proxy class defined by interfaces [interface com.example.WorkService, interface org.springframework.aop.SpringProxy, interface org.springframework.aop.framework.Advised, interface org.springframework.core.DecoratingProxy] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
```

I can get around this by just adding a `proxy.json` entry.

However, I'm wondering if there is a way to generalize this in the `@AutomaticFeature` impl. Perhaps for every interface `XXXXX` which fits the criteria, create a proxy entry like:

```
["XXXXX", "org.springframework.aop.SpringProxy", "org.springframework.aop.framework.Advised", 
 "org.springframework.core.DecoratingProxy"] 
```

via:

```
Class<?>[] classes = Arrays.stream(proxyClassesToAddList)
            .map(name -> access.findClassByName(name))
            .toArray(Class<?>[]::new);
DynamicProxyRegistry dynamicProxyRegistry = ImageSingletons.lookup(DynamicProxyRegistry.class);
dynamicProxyRegistry.addProxyClass(classes);
```

**Comment by aclement** [comment]
Hey,

Just on your final point, yes the feature could do that and indeed it is what happens for transactions - https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-configuration/src/main/java/org/springframework/TransactionalComponentProcessor.java - that componentprocessor, for components that are annotated transactional, will add proxies for the component type plus the handful of spring types. This situation might be another form of componentprocessor or a generalization of that transaction one to cover other cases.

> So is the solution to this problem to just create an interface for my WorkService class and inject that? Are GraalVM-compiled apps unable to inject a concrete class in certain situations?

I'm not a guru on this but I can imagine the need to use JDK proxies with GraalVM right now, and the limitation it brings that you can only implement interfaces with that kind of proxy could mean there are situations you need to introduce an interface. Did you try that?

**Comment by dzou** [comment]
@aclement - Ah yes I see. Yes I did end up introducing a new interface which worked for me. This might just be part of the list of things you need to do to get an application compatible with graalvm compilation.

Going to close as it is resolved.
