### ISSUE TITLE
Add Gradle documentation

### ISSUE THREAD

**Issue by benwilcock** [spring-projects-experimental/spring-graalvm-native#318]
I love Maven, I prefer it in fact and I use it all the time. But some folks feel the same way about Gradle. Any chance we can have Gradle instructions added into the documentation so that folks can choose the instruction that's right for them based on their preferred build tool? That would be brilliant - thanks in advance!

**Comment by sdeleuze** [comment]
We now have Gradle documentation for both Groovy and Kotlin DSLs.
![image](https://user-images.githubusercontent.com/141109/96511527-7f305880-125f-11eb-9a1c-b78a71b8f762.png)

**Comment by benwilcock** [comment]
Nice. Thank-you!
