### ISSUE TITLE
maven build-image stuck at running creator

### ISSUE THREAD

**Issue by sadew145** [spring-projects-experimental/spring-graalvm-native#322]
```
[INFO] Building image 'docker.io/library/uaa:1.7.0-SNAPSHOT'

[INFO] 

[INFO]  > Pulling builder image 'docker.io/paketobuildpacks/builder:tiny' 100%

[INFO]  > Pulled builder image 'paketobuildpacks/builder@sha256:a933b243b2df8cbcd8b2d2740c67297a1c05531de7bcd01b81c40dd3e16f3ed4'

[INFO]  > Pulling run image 'docker.io/paketobuildpacks/run:tiny-cnb' 100%

[INFO]  > Pulled run image 
'paketobuildpacks/run@sha256:22aca8769152f6aeedf27042a546e5df2d03f457124d7ec548c84d6cba34f2cc'

[INFO]  > Executing lifecycle version v0.9.1

[INFO]  > Using build cache volume 'pack-cache-3ed579b22c31.build'

[INFO] 
[INFO]  > Running creator
```

I tried to build an image with buildpack but it stuck at running creator 

when i tried to run docker with the image above mean while the creator is still running, it give me this login error even though I have not logged in on docker.

```
Unable to find image 'uaa:1.7.0-SNAPSHOT' locally
docker: Error response from daemon: pull access denied for uaa, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by nebhale** [comment]
@sadew145 Can you please provide the command that you're running, and if public, the repo that you're trying to run against?

**Comment by sadew145** [comment]
@nebhale I didn't use anything special. I only used the paketo basic settings like in the doc and run `mvn spring-boot:build-image` to build but it just never get anywhere

**Comment by nebhale** [comment]
@sadew145 Without being able to reproduce the problem (for example, by knowing the repository and command line you’re working with) we won’t be able to diagnose the issue.  We’ve not seen this behavior before, either during development or in the wild, so reproduction is the firs step.
