### ISSUE TITLE
Package name collision in spring graalvm native and spring kafka

### ISSUE THREAD

**Issue by don-mayur** [spring-projects-experimental/spring-graalvm-native#323]
There are two packages sharing exactly same  name

org.springframework.kafka.annotation
This package exists in spring-kafka as well as spring-graalvm-native artifact

This is resulting in below error after successfully compiling and trying to run spring native graalvm image

Caused by: java.io.FileNotFoundException: class path resource [org/springframework/kafka/annotation/KafkaBootstrapConfiguration.class] cannot be opened because it does not exist
Full log attached
[spring_native_graal_startup_error.log](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5360599/spring_native_graal_startup_error.log)

Is there any workaround?

**Comment by sadew145** [comment]
I would like to second a support for spring kafka please

**Comment by aclement** [comment]
Is it definitely the duplicate package situation that is causing an issue? I'm more likely to suspect that we've done no work to support Kafka. Gary started working on Kafka sample, we should pursue getting that working: https://github.com/garyrussell/spring-graalvm-native/tree/kafka/spring-graalvm-native-samples/kafka

**Comment by sadew145** [comment]
@don-mayur i was able to fix it by removing @EnableKafka in my boot app, boot should be able to pick it up as long as kafka is in class path. The image was built but ended up with 
` @Configuration classes need to be marked as proxyBeanMethods=false. Found: [org.springframework.retry.annotation.RetryConfiguration]
`
Currently I can't find a way to fix this other than requesting people to update spring-retry to disable proxy

**Comment by don-mayur** [comment]
@sadew145  We do have kafka starter and thus we don't explicitly specify`@EnableKafka` but it will be used, So I cannot remove it, moreover as you pointed out it might still fail if you I remove starter also.

**Comment by don-mayur** [comment]
@aclement That’s great that spring kafka official support is in works, to answer your question I think package situation won't solve all support issue for spring kafka. But I faced error(attached) while running native app.

**Comment by sadew145** [comment]
@don-mayur just to clarify, I dont remove kafka dep, I only remove @EnableKafka. Spring boot should be able to pick it up by itself. Also, it didn't fail because of kafka. If i build without native-image, the app runs normally with kafka enabled

**Comment by don-mayur** [comment]
@sadew145 Same for me, if I run normally it works just fine but when I compile it to native image that's when I face this issue while running native app

**Comment by sadew145** [comment]
@don-mayur i think you miss understand me. All i wanted to said is you dont need to have @EnableKafka to get kafka running when i compile my app with native image it runs ok only get blocked by spring-retry

**Comment by aclement** [comment]
I just pushed an initial kafka sample that is working. There are some tweaks we need to make so it works 'out of the box' (that will fix the problem like you have in the first comment 'classpath resource cannot be opened') but to get it going I just ran with the agent to collect valid config then built using that, crudely:
```
mkdir -p src/main/resources/META-INF/native-image
 java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image -jar target/kafka-0.0.1-SNAPSHOT.jar
```
Then a maven build using the native profile in the pom.xml.

**Comment by aclement** [comment]
I've polished the sample today - it no longer requires any agent collection. The feature supports everything this sample needs, and it builds and runs fine. Please take a look and if your usage of kafka differs, let's capture those differences in a test project and get that working too. Sample is in the project here: https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/kafka

**Comment by don-mayur** [comment]
@aclement I am facing Caused by: java.lang.NoSuchMethodException: org.springframework.context.annotation.ConfigurationClassParser$DefaultDeferredImportSelectorGroup.<init>()
with Kafka sample, I am attaching log for reference 
[spring-graal-native-kafka-sample-run-error.log](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5393373/spring-graal-native-kafka-sample-run-error.log)

**Comment by aclement** [comment]
Are you building spring-graalvm-native locally for yourself? If you aren't then you may be picking up an old snapshot of 0.8.2 that doesn't include the change for that (I doubt the build has finished yet). The current codebase includes the necessary hint for that: https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-configuration/src/main/java/org/springframework/context/annotation/ContextAnnotationHints.java#L47

**Comment by don-mayur** [comment]
You are right @aclement  I was not and now I tried and kafka sample is working for me. I can now close this issue. 
Although for my app some configurations file when marked with `proxyBeanMethod=false` then app fails while running even with normal spring-boot run.
