### ISSUE TITLE
Attribute 'value' in annotation @RestController is declared as an @AliasFor nonexistent attribute 'value' in annotation @Controller

### ISSUE THREAD

**Issue by sadew145** [spring-projects-experimental/spring-graalvm-native#329]
Hi, I am currently trying to build native image for one of my microservices as spring cloud client.

Attached  pom, bootstrap.yml, native-image/config jsons, and startup log. Liquibase and log4j was added to pom to remove some warning. Some config values was also removed for privacy purposes

In my configuration, I only included @EnableResourceServer, @EnableSwagger2, @SpringBootApplication, and @EnableFeignClients. 

I ran my config server in jvm due to limitation of PostEnvironmentProcessor preventing the config server from starting. ProfileApplication was able to start normally and load the config from config server. But, After loading config, I got this error:
`Attribute 'value' in annotation @RestController is declared as an @AliasFor nonexistent attribute 'value' in annotation @Controller`

Note: image was build on wsl ubuntu focal

[profile.zip](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5417912/profile.zip)

**Comment by aclement** [comment]
I suspect it is the processing we do not operating on some of the controllers found inherited from dependencies. Which dependency it is without a sample project, not quite sure. You could probably workaround it by manually creating an entry in `src/main/resources/META-INF/native-image/reflect-config.json`
looking like:
```
[
{"name":"org.springframework.stereotype.Controller","allDeclaredMethods":"true"}
]
```

**Comment by sadew145** [comment]
I will give it a try. Thank you

**Comment by sadew145** [comment]
Looks like that fixed it. Thanks. Closing this ticket now
