### ISSUE TITLE
Remove reflection entries from webmvc-tomcat

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#339]
Introduced by @dsyer via https://github.com/spring-projects-experimental/spring-graalvm-native/commit/021355eb5353958c80eb94312779be8d7dd2ca41. Not sure what to do about it

**Comment by dsyer** [comment]
Have you tried removing it? I think Andy already added extra registrations for nested classes in `@ConfigurationProperties`.

**Comment by sdeleuze** [comment]
It works without it indeed.
