### ISSUE TITLE
Agent builds are broken due to ClassNotFoundException

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#349]
[Agent builds are broken](https://ci.spring.io/teams/spring-graalvm-native/pipelines/spring-graalvm-native/jobs/20.3-dev-java11-samples-build/builds/2) with the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.graalvm.utils.LiteConfigurationInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:467)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:449)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:442)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:284)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at com.example.webflux.WebfluxApplication.main(WebfluxApplication.java:12)
Caused by: java.lang.ClassNotFoundException: org.springframework.graalvm.utils.LiteConfigurationInitializer
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1292)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:460)
	... 7 more
```

This class is referenced in [our own `spring.factories`](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-configuration/src/main/resources/META-INF/spring.factories).

**Comment by aclement** [comment]
I can't recreate this locally and I can't currently use the `run-dev-container.sh` on either my Mac or my linux...

**Comment by sdeleuze** [comment]
Some findings:
- Locally I can recreate it for `cloud` but not `webflux-netty`.
- I made the various `agent/build.sh` consistent, same issue
- I see the issue with `java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer` on my side
- The reflection file contains a `SharedMetadataReaderFactoryContextInitializer` referencing the noarg constructor
- If I just remove the `graal/META-INF/native-image` directory, same error

So it is like if the reflection file is not taken in account! Maybe a corrupted JSON file generated by the agent?

**Comment by sdeleuze** [comment]
More progresses:
 - `resource-config.json` processing previously broken due to https://github.com/oracle/graal/commit/5b0a7453bcfb09918d8f615e64bf0430c8abbbfc is now fixed
 - The error is likely triggered by the fact that `reflect-config.json` and/or `resource-config.son` are in the classpath because using command line `native-image` option instead works fine.
 - The difference with `webflux-netty ` that works has been identified: the failure is triggered by `spring-cloud-commons`

**Comment by sdeleuze** [comment]
If we remove manually `{"pattern":"\\QMETA-INF/spring.factories\\E"}`, from `resource-config.json`, no more error.

**Comment by aclement** [comment]
I think this might be a GraalVM issue to dig into. Suppose you have a type where the generics of one of the methods cannot be resolved because they aren't on the class path (e.g. `foo(List<SomethingNotOnClasspath> list)`). Specifying `allDeclaredMethods` you get away with it, but if you specifically name the methods then GraalVM throws a hard error trying to resolve the generics.

How does that relate to this overall issue?

If you have `spring.factories` in a resource configuration, the Spring GraalVM feature cannot add a modified version into the image, so it backs off and does not throw unused autoconfig away.  Throwing away unused config was getting rid of all these methods with unresolvable generics. If we don't throw it away they are included. But worse in the old days we would use `allDeclaredMethods` but more recently we are being specific about the `@Bean` methods in a configuration. Thus if you don't throw these types away *and* you are specific about the methods in the config -> you trigger the problem in the first paragraph of this comment.

So...

I have made it so we take extra care and try to avoid referencing these methods with unresolvable generics when computing the method lists for types we process. This fixes it for the case I have seen (`commandlinerunner` with `-Dspring.native.remove-unused-autoconfig=false`). There was also a smaller issue - we have some 'special cases' for discarding things, e.g. configuration related to JMX. Because we can't discard it with spring.factories in resource config, we have to allow for this case.  Let's see what the agent samples make of this on the build machine. I cannot recreate their problems right now locally (which is also strange...)

**Comment by aclement** [comment]
(Running with spring.factories in agent produced resource config is really not going to produce optimal images)

**Comment by sdeleuze** [comment]
I still can reproduce this issue, I see this error on `cloud-agent`:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:467)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:449)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:442)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:284)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at com.example.webflux.WebfluxApplication.main(WebfluxApplication.java:13)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1292)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:460)
	... 7 more
```
Since it works when config files are not in the classpath but specific with command line parameters, couldn't we just unplug totally our `spring.factories` rewrite mechanism when `spring.factories` is listed in resources?

**Comment by aclement** [comment]
> couldn't we just unplug totally our spring.factories rewrite mechanism when spring.factories is listed in resources?

We kinda do, but yes, perhaps not going far enough, it is quite complicated but I will have a look.  It may continue to break, for example, if hints are specifying exact methods and in some contexts those are non fully resolvable. But perhaps 'luckily' we don't do much of that exact specifying yet.

**Comment by aclement** [comment]
The message that comes out:
```
  System.out.println("WARNING: unable to trim META-INF/spring.factories (for example to disable unused auto configurations) because an existing resource-config is directly including it: "+existingRC);
```
is saying we are not attempting to change spring.factories, this is more about the analysis we do of the configurations themselves and effectively we have to perform weaker/dumber analysis when these kinds of unresolvable configurations are included. I do think there is a GraalVM issue here.

**Comment by sdeleuze** [comment]
Ok let's move that one to 0.9.0, I will skip the broken agent tests for now.

**Comment by aclement** [comment]
I switched to linux and found myself confused when the 20.3 release worked for me - what was different with the build machine? I discovered if you are using a labsjdk 'debug' underneath GraalVM things fail. If you use a non-debug labsjdk it works. So I was able to start recreating the problem on my Mac by rebuilding GraalVM with a debug labsjdk.

**Comment by sdeleuze** [comment]
I confirm what you found Andy, I have switched our container images to non-debug JDK and will raise an issue on GraalVM side.

**Comment by nfrankel** [comment]
I'm facing the same issue with a regular `spring-boot:build-image` and the following configuration:

```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <!-- Spring Boot Actuator displays build-related information
              if a META-INF/build-info.properties file is present -->
            <goals>
                <goal>build-info</goal>
            </goals>
            <configuration>
                <additionalProperties>
                    <encoding.source>${project.build.sourceEncoding}</encoding.source>
                    <encoding.reporting>${project.reporting.outputEncoding}</encoding.reporting>
                    <java.source>${maven.compiler.source}</java.source>
                    <java.target>${maven.compiler.target}</java.target>
                </additionalProperties>
            </configuration>
        </execution>
    </executions>
    <configuration>
        <image>
            <name>code-with:springboot</name>
            <builder>index.docker.io/paketobuildpacks/builder:tiny</builder>
            <runImage>index.docker.io/paketobuildpacks/run:tiny-cnb</runImage>
            <env>
                <BP_JVM_VERSION>11</BP_JVM_VERSION>
                <BP_BOOT_NATIVE_IMAGE>true</BP_BOOT_NATIVE_IMAGE>
                <BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>-Dpetclinic.security.enable=false -Dspring.profiles.active=postgres,spring-data-jpa --initialize-at-build-time=net.bytebuddy.implementation.bind.annotation.Super$Instantiation,net.bytebuddy.implementation.bind.annotation.Super$Instantiation$1,sun.instrument.InstrumentationImpl,net.bytebuddy.description.type.TypeDescription$AbstractBase,net.bytebuddy.description.type.TypeDescription$ForLoadedType,javax.el.MapELResolver,javax.el.ListELResolver,org.slf4j.impl.SimpleLogger,org.slf4j.impl.OutputChoice$1</BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS>
            </env>
        </image>
    </configuration>
</plugin>
```

**Comment by sdeleuze** [comment]
Likely to be reported on GraalVM side.
