### ISSUE TITLE
ResponseStatus on WebMVC annotated controllers lead cause an internal server error.

### ISSUE THREAD

**Issue by michael-simons** [spring-projects-experimental/spring-graalvm-native#357]
Given

```java
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class SomeController {

	@GetMapping
	String get() {
		return "Hallo\n";
	}

	@PostMapping
	@ResponseStatus(value = HttpStatus.CREATED)
	String post() {
		return "Hello\n";
	}
}
```

and 

```
@SpringBootApplication(proxyBeanMethods = false)
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```

The requests against `/` work on JVM mode and returning  `Hallo` and `Hello` with the correct status code.
Running as a native image inside the lightweight container makes `post` fail with a HTTP 500.

Reproducer is attached: [httpstatus.zip](https://github.com/spring-projects-experimental/spring-graalvm-native/files/5537184/httpstatus.zip)

Steps to run:

```
./mvnw -DskipTests clean spring-boot:build-image
docker  run --name xxx  -d  --publish=8080:8080 demo:0.0.1-SNAPSHOT 
curl -v  -X GET localhost:8080          
curl -v  -X POST localhost:8080
docker rm -f xxx
```

The later given you a 

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 500 
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 6
< Date: Fri, 13 Nov 2020 13:44:12 GMT
< Connection: close
< 
Hello
* Closing connection 0
```

As you see, the controller is actually executed, but something afterwards fails.

The reproducer is 2.4.0-RC1 + native 0.8.2.
I couldn't get 2.4.0 to build natively, neither with 0.8.2 nor 0.8.3 snapshot

**Comment by aclement** [comment]
Just needed to add hints so reflection could see the HttpStatus/ResponseStatus. Thanks for the sample, used that to verify.

**Comment by aclement** [comment]
Rather than adding these directly as hints we could enhance `WebComponentProcessor` to only do it if needed in the future.
