### ISSUE TITLE
How to run JUnit tests in native image?

### ISSUE THREAD

**Issue by dzou** [spring-projects-experimental/spring-graalvm-native#359]
Hello!

I'm one of the engineers working on GraalVM support for the [Google Java client libraries](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support) and on Spring Cloud GCP. We've been following this repo closely and learning from your work, very excited to see your progress.

One question that we had is regarding how to run JUnit tests in native image for validation purposes.

I saw there was some work done here https://github.com/spring-projects-experimental/spring-graalvm-native/issues/22 but I wasn't quite able to figure out how it worked entirely.

If you could point us in the right direction this would be greatly appreciated; just some code locations would be very helpful!

cc/ @meltsufin

**Comment by sdeleuze** [comment]
Hey, thanks for reaching out, we plan to work on a joint effort with GraalVM team on this, we will share more in the upcoming weeks. I will update this issue when we will have more to share.

**Comment by dzou** [comment]
I see, thanks @sdeleuze - looking forward to hearing any new updates on this.

Just curious - How long do you think we may have to wait for something to be announced?

**Comment by sdeleuze** [comment]
We will provide an update early December, please subscribe to #22 to follow our progress on that.
