### ISSUE TITLE
Release for Spring Boot 2.4.0

### ISSUE THREAD

**Issue by jkroepke** [spring-projects-experimental/spring-graalvm-native#360]
Hi,

the current released version 0.8.2 isn't compatible with Spring Boot 2.4.0.

Do you have a planned release date for 0.8.3?

I know, I could [fetch](https://repo.spring.io/snapshot/org/springframework/experimental/spring-graalvm-native/0.8.3-SNAPSHOT/) a snapshot for 0.8.3 but I can't pin the snapshot version and I don't want to use floating artifacts in my project..

**Comment by sdeleuze** [comment]
Yes, the release date specified on https://github.com/spring-projects-experimental/spring-graalvm-native/milestones is expected to be up-to-date.
