### ISSUE TITLE
Update the documentation to support only current Boot version

### ISSUE THREAD

**Issue by tibberg** [spring-projects-experimental/spring-graalvm-native#370]
I was following the getting started guide (https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.2/spring-graalvm-native-docs-0.8.2.zip!/reference/index.html#_getting_started) and if I set the parent project's version to 2.4.0 the build was not successful. I got the following error (both buildpack and the native-image maven plugin):

```
Error: Classes that should be initialized at run time got initialized during image building:                                                                                                  
 org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory was unintentionally initialized at build time. To see why org.springframework.boot.logging.logback.LogbackLoggingSystem
$Factory got initialized use --trace-class-initialization=org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory                                                               
org.springframework.boot.logging.java.JavaLoggingSystem$Factory was unintentionally initialized at build time. To see why org.springframework.boot.logging.java.JavaLoggingSystem$Factory got 
initialized use --trace-class-initialization=org.springframework.boot.logging.java.JavaLoggingSystem$Factory                               ``

**Comment by sdeleuze** [comment]
Yeah that's expected and [documented](https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.2/spring-graalvm-native-docs-0.8.2.zip!/reference/index.html#_spring_boot). 0.8.3 is just around the corner, so you won't have to wait too much ;-)

**Comment by tibberg** [comment]
just a tiny addition, here it says 2.4.0-RC1 or above.
https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.2/spring-graalvm-native-docs-0.8.2.zip!/reference/index.html#_update_the_build_file

**Comment by sdeleuze** [comment]
Good point, I will update the doc accordingly thanks.
