### ISSUE TITLE
Not able to turn off boot banner when using 0.8.3

### ISSUE THREAD

**Issue by trisberg** [spring-projects-experimental/spring-graalvm-native#376]
We have `spring.main.banner-mode=off` in the `application.properties` but even though this file is included in `resource-config.json` we get the boot banner when the app starts.

In addition we can't turn it off using an env var either.

```
% SPRING_MAIN_BANNER_MODE=OFF ./tss-new-cli/target/tss -h

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.0)

Usage: tss [-h] [COMMAND]
  -h, --help   Display this help
Commands:
  starter    Create and list starters
  generator  Create, list, update, and delete generators
  project    Create a new project
```

**Comment by aclement** [comment]
can you turn it off in your app main whilst we dig into it?

**Comment by trisberg** [comment]
yes, will do that for now, thanks

**Comment by aclement** [comment]
We removed reflective config for `SpringApplication.class` to save vast amounts of image size (like 5m on commandlinerunner). Unfortunately that was going too far. We at least need `setBannerMode` access to enable property control of the banner to work. I've added reflective access to just this method, and property control is working.
