### ISSUE TITLE
logback  DEBUG log level is ALWAYS printed after  compiled to exe

### ISSUE THREAD

**Issue by doujs** [spring-projects-experimental/spring-graalvm-native#388]
After compiled to Exe , the output format for everything is **ALWAYS DEBUG** , no matter whatever log level is set in application.properties :
-----------
18:44:48.655 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - Listing entities:
18:44:48.655 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=5, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=6, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=3, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=4, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=dou, ctime=null, id=1, schoolName=bj}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=free, ctime=null, id=2, schoolName=nj}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=13, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=14, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=11, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=12, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=9, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=10, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=7, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=8, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=21, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=22, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=19, schoolName=Middle}
18:44:48.656 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=20, schoolName=Middle}
18:44:48.657 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=17, schoolName=Middle}
18:44:48.657 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=18, schoolName=Middle}
18:44:48.657 [http-nio-8081-exec-1] DEBUG org.hibernate.internal.util.EntityPrinter - com.test.aha.Student{name=new, ctime=null, id=15, schoolName=Middle}

=====================
And when I decide to add a logback.xml to hava a try , it needs lots of initialize-at-build-time setting.
---------

rror: Classes that should be initialized at run time got initialized during image building:
 com.sun.org.apache.xerces.internal.util.XMLChar was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.XMLChar has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.XMLChar
com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl
com.sun.org.apache.xerces.internal.impl.XMLScanner was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLScanner has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLScanner
com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl
com.sun.org.apache.xerces.internal.util.XMLSymbols was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.XMLSymbols has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.XMLSymbols
com.sun.org.apache.xerces.internal.impl.XMLEntityManager was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLEntityManager has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLEntityManager
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl
com.sun.org.apache.xerces.internal.impl.Constants was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.Constants has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.Constants
com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl
com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator
com.sun.org.apache.xerces.internal.util.FeatureState was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.FeatureState has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.FeatureState
com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator was unintentionally initialized at build time. com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator
com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDProcessor was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDProcessor has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDProcessor
com.sun.org.apache.xerces.internal.impl.XMLEntityScanner was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLEntityScanner has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLEntityScanner
com.sun.org.apache.xerces.internal.xni.NamespaceContext was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.xni.NamespaceContext has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.xni.NamespaceContext
com.sun.org.apache.xerces.internal.impl.XMLEntityManager$EncodingInfo was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLEntityManager$EncodingInfo has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLEntityManager$EncodingInfo
jdk.xml.internal.JdkXmlUtils was unintentionally initialized at build time. jdk.xml.internal.JdkXmlUtils has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=jdk.xml.internal.JdkXmlUtils
com.sun.org.apache.xerces.internal.util.PropertyState was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.PropertyState has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.PropertyState
com.sun.org.apache.xerces.internal.impl.XMLVersionDetector was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLVersionDetector has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLVersionDetector
com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.sun.org.apache.xerces.internal.util.XMLChar was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.XMLChar has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.XMLChar
com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl
com.sun.org.apache.xerces.internal.impl.XMLScanner was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLScanner has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLScanner
com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dv.dtd.DTDDVFactoryImpl
com.sun.org.apache.xerces.internal.util.XMLSymbols was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.XMLSymbols has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.XMLSymbols
com.sun.org.apache.xerces.internal.impl.XMLEntityManager was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLEntityManager has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLEntityManager
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl
com.sun.org.apache.xerces.internal.impl.Constants was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.Constants has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.Constants
com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl
com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator
com.sun.org.apache.xerces.internal.util.FeatureState was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.FeatureState has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.FeatureState
com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator was unintentionally initialized at build time. com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.xml.internal.stream.util.ThreadLocalBufferAllocator
com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDProcessor was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDProcessor has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDProcessor
com.sun.org.apache.xerces.internal.impl.XMLEntityScanner was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLEntityScanner has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLEntityScanner
com.sun.org.apache.xerces.internal.xni.NamespaceContext was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.xni.NamespaceContext has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.xni.NamespaceContext
com.sun.org.apache.xerces.internal.impl.XMLEntityManager$EncodingInfo was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLEntityManager$EncodingInfo has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLEntityManager$EncodingInfo
jdk.xml.internal.JdkXmlUtils was unintentionally initialized at build time. jdk.xml.internal.JdkXmlUtils has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=jdk.xml.internal.JdkXmlUtils
com.sun.org.apache.xerces.internal.util.PropertyState was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.util.PropertyState has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.util.PropertyState
com.sun.org.apache.xerces.internal.impl.XMLVersionDetector was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.XMLVersionDetector has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.XMLVersionDetector
com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator was unintentionally initialized at build time. com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator

---------
Can I change the default log level to debug or  can I add a logback.xml file without so many initialize-at-build-time classes

**Comment by sdeleuze** [comment]
Indeed I can reproduce, I have created a 0.8.4 milestone in order to fix that without waiting too much.

**Comment by sdeleuze** [comment]
My mistake, I can't reproduce.
