### ISSUE TITLE
How can I use GraalVm agentlib in graalvm version 20.3.0

### ISSUE THREAD

**Issue by ahTy** [spring-projects-experimental/spring-graalvm-native#403]
How can I use GraalVm's reflection configuration assistant tool agentlib to assist in generating relevant configuration files in my spring cloud project (springcloud version 2020.0.0-SNAPSHOT, springboot version 2.4.0, graalvm version 20.3.0)

When i try to use
‘java -agentlib:native-image-agent=config-output-dir=./native-image/ -jar myproject.jar’
it break down and return me core error
![image](https://user-images.githubusercontent.com/28003201/101853826-447dd900-3b9b-11eb-8572-fd4b28d87112.png)

I need to import my own configuration file in my spring cloud project  and use agentlib to export the corresponding reflection configuration

**Comment by ahTy** [comment]
error info：
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdb5418248a, pid=19138, tid=0x00007fdb5764a700
#
# JRE version: OpenJDK Runtime Environment (8.0_272-b10) (build 1.8.0_272-b10)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (25.272-b10-jvmci-20.3-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnative-image-agent.so+0x5248a]
#
# Core dump written. Default location: ./core or core.19138
#
# An error report file with more information is saved as:
# ./hs_err_pid19138.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by sdeleuze** [comment]
Please report this bug on https://github.com/oracle/graal/issues and attach the `hs_err_pid19138.log` file.
