### ISSUE TITLE
Downloading graalvm-ce within the Gradle task is unbelievable slow

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects-experimental/spring-graalvm-native#411]
Downloading https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.3.0/graalvm-ce-java11-linux-amd64-20.3.0.tar.gz within the Gradle task sometimes takes hours. It would be nice to have an option to specify a local installation path.

Please see this screenshot for the ultra-slow download speed while other accesses to GitHub work fine:
![grafik](https://user-images.githubusercontent.com/734334/102255099-dbcf8d00-3f09-11eb-97ac-b9dc0b908985.png)

**Comment by jamesward** [comment]
Note that the Gradle Graal plugin caches it: https://github.com/palantir/gradle-graal
(Which might be harder with buildpacks)

**Comment by bclozel** [comment]
See paketo-buildpacks/java#86

**Comment by juergenzimmermann** [comment]
@bclozel Setting `pullPolicy = org.springframework.boot.buildpack.platform.build.PullPolicy.IF_NOT_PRESENT` for the Gradle task `bootBuildImage` doesn't change anything.

**Comment by uqix** [comment]
@juergenzimmermann just FYI

https://paketo.io/docs/buildpacks/configuration/#bindings

https://paketo.io/docs/buildpacks/language-family-buildpacks/java/#connecting-to-a-private-maven-repository

https://github.com/spring-projects/spring-boot/issues/24556

https://github.com/paketo-buildpacks/bellsoft-liberica/issues/7

We have similar situation as yours,  I have set up a proxy to speed up the download, but springboot maven `build:image` just downloads some files every run that slows down our CI/CD pipeline so much that I have to pass a Binding to replace the urls  with local ones.

**Comment by sdeleuze** [comment]
Please raise this issue on Paketo buildpack side, maybe as a comment on https://github.com/paketo-buildpacks/java/issues/86.
