### ISSUE TITLE
Add support for Jackson Java7 handlers

### ISSUE THREAD

**Issue by hakandilek** [spring-projects-experimental/spring-graalvm-native#420]
Hello everyone,

I'm not sure if this is something that needs to be solved by `spring-graalvm-native` or how it should be handled though here is the problem:

When I run the application. upon first HTTP-Request I get this logging:

```
 Dec 18, 2020 6:03:42 PM com.fasterxml.jackson.databind.ext.Java7Handlers <clinit>
 WARNING: Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added
```

This is where the instance of `com.fasterxml.jackson.databind.ext.Java7HandlersImpl` is being created via reflection:

(from `com.fasterxml.jackson.databind.ext.Java7Handlers`)
```
    private final static Java7Handlers IMPL;

    static {
        Java7Handlers impl = null;
        try {
            Class<?> cls = Class.forName("com.fasterxml.jackson.databind.ext.Java7HandlersImpl");
            impl = (Java7Handlers) ClassUtil.createInstance(cls, false);
        } catch (Throwable t) {
            // 09-Sep-2019, tatu: Could choose not to log this, but since this is less likely
            //    to miss (than annotations), do it
            java.util.logging.Logger.getLogger(Java7Handlers.class.getName())
                .warning("Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added");
        }
        IMPL = impl;
    }
```

**Comment by spencergibb** [comment]
This only supports java 11 and up, not sure if that makes a difference #350

**Comment by hakandilek** [comment]
> This only supports java 11 and up, not sure if that makes a difference #350

Yes, I'm on 11:
```
GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
```

**Comment by aclement** [comment]
We have other hints for Jackson, I'm not against extending that a little. I've seen these warnings too but they haven't broken anything so haven't done anything about them.

Can you calculate the suitable reflect configuration for what you want to work? Then we can work that into the hints.  This involves:

- create a file `src/main/resources/META-INF/native-image/reflect-config.json`

- in that file, for anything that is not being reflected upon, add an entry a bit like this.
```
[
 {
    "name": "kotlin.KotlinVersion", 
    "allPublicMethods": true,
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  }
]
```
multiple {...} blocks potentially, one for each type. As for the 'all...' flags, you may not need them all. If the code only needs to construct the type, specify the `allDeclaredConstructors` line. It may then be calling the methods directly, but if it additionally needs to call those by reflection, add `allDeclaredMethods` or `allPublicMethods` lines.

native-image will auto find that config file and apply it. If you work out the configuration that works, we can fold it into 
https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-configuration/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonHints.java

**Comment by hakandilek** [comment]
@aclement thanks for the help.This one seems to be enough for a fix:

```
[
  {
    "name": "com.fasterxml.jackson.databind.ext.Java7HandlersImpl",
    "allPublicConstructors":true
  }
]
```

But I suppose we might need another entry for `Java7SupportImpl` for a complete fix:

```
[
  {
    "name": "com.fasterxml.jackson.databind.ext.Java7HandlersImpl",
    "allPublicConstructors":true
  },
  {
    "name": "com.fasterxml.jackson.databind.ext.Java7SupportImpl",
    "allPublicConstructors":true
  }
]
```

I this case `JacksonHints.java` should be extended with the following, right?

```
@TypeInfo(types = Java7HandlersImpl, access = AccessBits.LOAD_AND_CONSTRUCT),
@TypeInfo(types = Java7SupportImpl, access = AccessBits.LOAD_AND_CONSTRUCT),
```

I'll prepare a PR if you think it's ok.

**Comment by sdeleuze** [comment]
It is probably better to just initialize those classes at build time, I will do this change and ask for tests on snapshots.

**Comment by hakandilek** [comment]
> It is probably better to just initialize those classes at build time, I will do this change and ask for tests on snapshots.

Yes, sure.
