### ISSUE TITLE
Fix and restore security and batch samples

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-graalvm-native#69]
Fix and restore `gs-securing-web` and `spring-batch-native` available from [security-and-batch-samples](https://github.com/spring-projects-experimental/spring-graal-native/tree/security-and-batch-samples) branch.

**Comment by aclement** [comment]
First pass at batch sample done - it does actually work, but it is currently reliant on config generated via agent. Would like to work that into hints for 0.7.

**Comment by aclement** [comment]
The security sample is kinda ready to go but I do have to remove that substitution for logging (Target_LogAdapter) - @sdeleuze are we ok to do that now? I saw it was related to some fixes we needed that might be there by now.

**Comment by aclement** [comment]
gs-securing-web sample is in too. I'm leaving this open whilst I decide what to do with the static configuration provided (agent generated) in these samples. Should the feature be enhanced to not need it?

**Comment by sdeleuze** [comment]
I would vote for closing it in its current state for 0.7 and polish the feature in 0.8.

**Comment by sdeleuze** [comment]
Batch samples are now broken due to https://github.com/spring-projects-experimental/spring-graalvm-native/commit/8f51461215c3c71ddf59a7113bb887d4d7097a7f, but I would like to keep this `proxyBeanMethods=false` hard check in order to push all Spring projects to not using CGLIB proxies for their configuration and avoid to have half broken configurations (a log message could be easily be missed).

I have asked @mminella to have a look if we could do something here.

**Comment by aclement** [comment]
gs-securing-web is now static configuration free. Will leave batch until other issue resolved. Not planning on doing any more here for 0.7
